all: forwarding1 forwarding2 forwarding3 forwarding4 forwarding_fun

forwarding1: forwarding1.cpp
	clang++ --std=c++2a -O2 -g forwarding1.cpp -o output1

forwarding2: forwarding2.cpp
	clang++ --std=c++2a -O2 -g forwarding2.cpp -o output2

forwarding3: forwarding3.cpp
	clang++ --std=c++2a -O2 -g forwarding3.cpp -o output3

forwarding4: forwarding4.cpp
	clang++ --std=c++2a -O2 -g forwarding4.cpp -o output4

forwarding_fun: forwarding_galaxybrain.cpp
	clang++ --std=c++2a -O2 -g forwarding_galaxybrain.cpp -o output_fun


.PHONY: all
